# nome do workflow
name: Deploy automatizado

# quando e onde aplicá-lo - quando houver push na branch develop
on: 
  push:
    branches: [ develop ]

# serviços executados
jobs:
  deploy-front:
    name: deploy front-end - vite react
    runs-on: ubuntu-latest
    # ações executadas no serviço
    steps:
    - name: Conectar no servidor VPS via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        # scripts / comandos que serão executados dentro do seu servidor
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd /var/app/github-actions
          git checkout develop
          git pull origin develop
          yarn
          yarn build
          cp -r dist/. /var/www/subdomain/github-actions/public_html/
          sudo systemctl reload apache2